version: "3"

networks:
  frontend:
  backend:

services:
  nginx:
    container_name: "nginx"
    networks:
      - frontend
      - backend
    build: "./nginx/"
    ports:
      - "80:80"
    volumes:
      - "./nginx/etc/nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/var/www/html:/var/www/html"
      - "./nginx/var/log/nginx:/var/log/nginx"

  php:
    container_name: "php"
    networks:
      - backend
    build: "./php/"
    expose:
      - 9000
    volumes:
      - "./nginx/var/www/html:/var/www/html"

  mysql:
    container_name: "mysql"
    networks:
      - backend
    ports:
      - "3306:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: mysqld --max_allowed_packet=1024M
    volumes:
      - "./mysql/var/lib/mysql:/var/lib/mysql"

  phpmyadmin:
      container_name: phpmyadmin
      networks:
        - frontend
        - backend
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      environment:
        PMA_HOST: mysql