version: "3"
services:
  # 服務名稱 nginx
  nginx:
    # 建立 image
    build:
      # dockerfile 目錄位置
      context: ./nginx
      # dockerfile 名稱
      dockerfile: Dockerfile
    # container 的名稱
    container_name: website
    # 外部與 container 內部的 port 對應
    ports:
      - 80:80
      - 443:443
    # 外部路徑 => container 路徑
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www/html
    # 指定連結的服務
    links:
      - php-fpm
  # 服務名稱
  php-fpm:
    # 建立 image
    build:
      # dockerfile 目錄
      context: ./php-fpm
      # dockerfile 名稱
      dockerfile: Dockerfile
    # container 名稱
    container_name: phpfpm
    # 開啟的 ports
    expose:
      - 9000
    # 外部路徑 => container 路徑
    volumes:
      - ./nginx/www:/var/www/html
    # 指定連結的服務
    links:
      - mysql
  # 服務名稱
  mysql:
    # 建立 image
    build:
      # dockerfile 目錄
      context: ./mysql
      # dockerfile 名稱
      dockerfile: Dockerfile
    # container 名稱
    container_name: mysql
    # 外部與 container 內部的 port 對應
    ports:
      - 3306:3306
    # 外部路徑 => container 路徑
    volumes:
      - ./mysql/data:/var/lib/mysql
  # 服務名稱
  phpmyadmin:
    # container 名稱
    container_name: phpmyadmin
    # image
    image: phpmyadmin/phpmyadmin
    # 預設的 port
    ports:
      - 8080:80
    # 指定連結的服務
    links:
      - mysql
    # 環境設定
    environment:
      # 連接位置
      PMA_HOST: mysql
